#######################
# config 
#######################
config:
  metadata:
    resource:
      name: flask-resouce
    env:
      name: flask-env
  data:
    memory-request: "128Mi"
    memory-limit: "256Mi"
    cpu-request: "250m"
    cpu-limit: "500m"
    host: "memcached-service"
    port: "11211"
    os: "kubernetes"

#######################
# deployment 
#######################
deployment:
  metadata:
    name: flask-app-deployment
  spec:
    replicas:
      count: 2
  container:
    name: flask-app-container
    image: dockerelvis/python-memcached:${VERSION}
    port: 8095
    readinessProbe:
      port: 8095
      initialDelaySeconds: 10
      periodSeconds: 15
    livenessProbe:
      port: 8095
      initialDelaySeconds: 20
      periodSeconds: 300
    volume:
      name: flask-app-volume
      claim: 
        name: nfs-pvc
    terminationGracePeriodSeconds:
      count: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

#######################
# ingress
#######################
ingress:
  metadata:
    name: flask-app-ingress
  spec:
    rules: 
      dns:
        host: my-flask-app.com
      number:
        port: 8096

#######################
# service
#######################
service:
  metadata:
    name: flask-app-service
  spec:
    service:
      exposePort: 8096
    container:
      targetPort: 8095