apiVersion: v1
kind: Namespace
metadata:
  name: stage
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: monitoring
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: stage
spec:
  storageClassName: "nfs" # dynamic provisioning
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 90Gi

