apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.resource.config.name }}
  labels:
    app: memcached
data:
  memory-request: "{{ .Values.data.memory_request }}"
  memory-limit: "{{ .Values.data.memory_limit }}"
  cpu-request: "{{ .Values.data.cpu_request }}"
  cpu-limit: "{{ .Values.data.cpu_limit }}"
