version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ec2-user/app/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_containers.sh
      timeout: 300
