services:
  flask-app:
    image: dockerelvis/python-memcached:latest
    container_name: flask-container
    ports:
      - "8096:8095"  # Map port 8095 of the container to 8096 on the host
    depends_on:
      - memcached
    environment:
      - FLASK_ENV=development
      - OPERATING_SYSTEM=docker-compose
      - MEMCACHED_HOST=memcached
    networks:
      - my_network
    volumes:
      - flask-app-data:/src
      # Mount the external volume to a path inside the container
      # The /src must exist i source code
#    entrypoint: ["python", "application.py"]
    restart: always  # Ensure the service restarts if it fails or Docker restarts

  memcached:
    image: memcached:latest
    container_name: memcached-container
    ports:
      - "11211:11211"  # Map the Memcached default port
    networks:
      - my_network
    volumes:
      - memcached-data:/var/lib/memcached  # Mount external volume for persistent Memcached data
    restart: always  # Ensure the service restarts if it fails or Docker restarts

networks:
  my_network:
    driver: bridge  # Default driver

volumes:
  flask-app-data:
    external: true  # Declare an external volume for the Flask app
  memcached-data:
    external: true  # Declare an external volume for Memcached
