#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.


- name: Install and configure Amazon CloudWatch Agent
  hosts: worker
  remote_user: kube_user
  become: yes
  gather_facts: true
  tasks:
    - name: Update the apt package list
      apt:
        update_cache: yes

    - name: Download the Amazon CloudWatch Agent package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb

    - name: Install the Amazon CloudWatch Agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Create CloudWatch Agent configuration file
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
              "agent": {
                  "metrics_collection_interval": 60,
                  "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
              },
              "metrics": {
                  "append_dimensions": {
                      "InstanceId": "${aws:InstanceId}"
                  },
                  "metrics_collected": {
                      "cpu": {
                          "measurement": [
                              "cpu_usage_idle",
                              "cpu_usage_system",
                              "cpu_usage_user"
                          ],
                          "metrics_collection_interval": 60,
                          "totalcpu": true
                      },
                      "disk": {
                          "measurement": [
                              "used_percent"
                          ],
                          "metrics_collection_interval": 60,
                          "resources": [
                              "/"
                          ]
                      },
                      "mem": {
                          "measurement": [
                              "mem_used_percent"
                          ],
                          "metrics_collection_interval": 60
                      }
                  }
              }
          }

    - name: Start and enable the Amazon CloudWatch Agent service
      systemd:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes

    - name: Verify the CloudWatch Agent service status
      shell: systemctl status amazon-cloudwatch-agent
      register: service_status

    - name: Print CloudWatch Agent service status
      debug:
        var: service_status.stdout

    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"  # Adjust based on your system's family

    - name: Install boto3 and botocore
      pip:
        name:
          - boto3
          - botocore
        state: present
      become: yes

    - name: Create CloudWatch Log Group via AWS CLI
      shell: aws logs create-log-group --log-group-name eksnode-log-group
      register: log_group_creation
      ignore_errors: yes


    - name: Print Log group status
      debug:
        var: log_group_creation.stdout

