
replicas: 1

StatefulSet:
  name: memcached-statefulset 
container:
  name: memcached-container
  image:
    repository: memcached
    tag: 1.6.21 
  port:
    number: 11211
volumeMounts:
  name: memcached-storage
volume:
  claim: 
    name: nfs-pvc

service:
  name: memcached-service
  port:
    number: 11211

resource:
  config:
    name: memcached-resouce
data:
  memory_request: "64Mi"
  memory_limit: "128Mi"
  cpu_request: "250m"
  cpu_limit: "500m"