apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs  # Ensure this matches your PVC's StorageClass
  nfs:
    path: /export  # Path to your NFS export
    server: nfs-provisioner.default.svc.cluster.local
  # Your NFS server's address
