apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.spec.service.exposePort }}  # Port exposed by the Service
      targetPort: {{ .Values.service.spec.container.targetPort }} # Port on the Pod
  type: LoadBalancer